-- AlterTable
ALTER TABLE `schedule_history` MODIFY `event` ENUM('CREATED', 'RESCHEDULED', 'STAGE_COMPLETED', 'STAGE_CANCELLED', 'STAGE_DELETED', 'PROJECT_CANCELLED', 'MANUAL_OVERRIDE', 'CAPACITY_RELEASED', 'DELIVERY_RECOMPUTED', 'MODE_CHANGED') NOT NULL;
